#%RAML 1.0
---

title: Individual PAYE Test Support
version: 2.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Usage
   content: !include docs/usage.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

types:
  nino:
    type: string
    pattern: ^((?!(BG|GB|KN|NK|NT|TN|ZZ)|(D|F|I|Q|U|V)[A-Z]|[A-Z](D|F|I|O|Q|U|V))[A-Z]{2})[0-9]{6}[A-D]?$
    example: AA000001A

/individual-paye-test-support:
  /paye:
    /nino:
      /{nino}:
        uriParameters:
          nino:
            description: The National Insurance number for the test data being created
            type: nino
        /tax-year:
          /{taxYear}:
            uriParameters:
              taxYear:
                description: The tax year for the test data being created.
                type: types.taxYear
            post:
              displayName: Create PAYE test data
              description:
              is: [headers.acceptHeader, headers.contentHeader]
              securedBy: [sec.x-application]
              body:
                application/json:
                  schema: !include schemas/create-tax-history-request.json
                  example: !include examples/create-tax-history-request.json
              responses:
                201:
