#%RAML 1.0
---

title: Individual PAYE Test Support
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml


/individual-paye-test-support:
  /sa:
    /{utr}:
      uriParameters:
        utr:
          description: The 10 digit self assessment UTR for the individual.
          type: string
          example: "2234567890"
      /benefits:
        /annual-summary:
          /{taxYear}:
            uriParameters:
              taxYear:
                description: The tax year for the benefits test data being created.
                type: types.taxYear
            post:
              displayName: Create benefits summary test data
              description: Supports the [Individual Benefits API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-benefits) by creating benefits summary test data.
              is: [headers.acceptHeader, headers.contentHeader]
              securedBy: [ sec.x-application ]
              body:
                application/json:
                  schema: !include schemas/create-summary-request-benefits.json
                  example: !include examples/create-individual-benefit-request.json
              responses:
                201:
                  body:
                    application/json:
                      schema: !include schemas/create-summary-request-benefits-response.json
                      example:
                        description: Example response for scenario HAPPY_PATH_1
                        value: !include examples/create-individual-benefit-response.json

      /employments:
        /annual-summary:
          /{taxYear}:
            uriParameters:
              taxYear:
                description: The tax year for the employment test data being created.
                type: types.taxYear
            post:
              displayName: Create employment history test data
              description: Supports the [Individual Employment API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-employment) by creating employment history test data.
              is: [headers.acceptHeader, headers.contentHeader]
              securedBy: [ sec.x-application ]
              body:
                application/json:
                  schema: !include schemas/create-summary-request-employment.json
                  example: !include examples/create-individual-employment-request.json
              responses:
                201:
                  body:
                    application/json:
                      schema: !include schemas/create-summary-request-employment-response.json
                      example:
                        description: Example response for scenario HAPPY_PATH_1
                        value: !include examples/create-individual-employment-response.json

      /income:
        /annual-summary:
          /{taxYear}:
            uriParameters:
              taxYear:
                description: The tax year for the income test data being created.
                type: types.taxYear
            post:
              displayName: Create annual income summary test data
              description: Supports the [Individual Income API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-income) by creating annual income test data.
              is: [headers.acceptHeader, headers.contentHeader]
              securedBy: [ sec.x-application ]
              body:
                application/json:
                 schema: !include schemas/create-summary-request-income.json
                 example: !include examples/create-individual-income-request.json
              responses:
                201:
                  body:
                    application/json:
                      schema: !include schemas/create-summary-request-income-response.json
                      example:
                        description: Example response for scenario HAPPY_PATH_1
                        value: !include examples/create-individual-income-response.json

      /tax:
        /annual-summary:
          /{taxYear}:
            uriParameters:
              taxYear:
                description: The tax year for the tax test data being created.
                type: types.taxYear
            post:
              displayName: Create tax summary test data
              description: Supports the [Individual Tax API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-tax) by creating annual tax test data.
              is: [headers.acceptHeader, headers.contentHeader]
              securedBy: [ sec.x-application ]
              body:
                application/json:
                  schema: !include schemas/create-summary-request-tax.json
                  example: !include examples/create-individual-tax-request.json
              responses:
                201:
                  body:
                    application/json:
                      schema: !include schemas/create-summary-request-tax-response.json
                      example:
                        description: Example response for scenario HAPPY_PATH_1
                        value: !include examples/create-individual-tax-response.json
